In [2]:
import sys
print(sys.executable)
import pandas as pd
print(pandas.__version__)

/Users/iketanimotoki/Desktop/練習場/PracticeFDev/PyData_train/.venv/bin/python

NameError: name 'pandas' is not defined

In [3]:
import sys
print(sys.executable)
import pandas as pd
print(pd.__version__)

/Users/iketanimotoki/Desktop/練習場/PracticeFDev/PyData_train/.venv/bin/python
3.0.3

In [5]:
import pandas as pd

In [8]:
df_train = pd.read_csv("./data/tamed/tamed_1.csv")
df_train.head(20)

          年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)
0    2025/1/1      5.9     12.1      1.9
1    2025/1/2      6.2     12.3      1.1
2    2025/1/3      6.4     11.0      3.5
3    2025/1/4      5.0      9.1      2.6
4    2025/1/5      4.6     10.0      0.1
5    2025/1/6      6.1      8.0      3.6
6    2025/1/7      5.4      9.3      1.9
7    2025/1/8      3.4      8.0      0.3
8    2025/1/9      2.7      8.0     -0.6
9   2025/1/10      1.1      4.7     -2.0
10  2025/1/11      3.6      7.2      1.0
11  2025/1/12      4.2      9.2      1.7
12  2025/1/13      4.5      9.8      0.7
13  2025/1/14      5.7     10.5      0.2
14  2025/1/15      5.6      9.4      2.5
15  2025/1/16      4.7      8.3      1.5
16  2025/1/17      4.5      8.0      2.4
17  2025/1/18      5.4     10.8      2.3
18  2025/1/19      7.5     14.7      1.8
19  2025/1/20      9.0     13.5      6.4

In [11]:
df_train.shape

(365, 4)

In [12]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   年月日      365 non-null    str
 1   平均気温(℃)  365 non-null    float64
 2   最高気温(℃)  365 non-null    float64
 3   最低気温(℃)  365 non-null    float64
dtypes: float64(3), str(1)
memory usage: 11.5 KB

In [13]:
df_train.describe()

          平均気温(℃)     最高気温(℃)     最低気温(℃)
count  365.000000  365.000000  365.000000
mean    17.560000   22.601918   13.538356
std      9.491771    9.910031    9.493703
min     -0.200000    4.000000   -3.400000
25%      8.700000   13.500000    4.900000
50%     17.000000   22.600000   12.200000
75%     26.900000   31.300000   23.200000
max     32.900000   39.600000   29.300000